"""empty message

Revision ID: 4d4db505b71c
Revises: 554e635e2197
Create Date: 2024-06-16 01:01:37.685763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4db505b71c'
down_revision = '554e635e2197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('subscriber_user_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('isAccepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscriber_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
